# prefixキーをC-aに変更する
set -g prefix C-a

# デフォルトのprefixキーC-bを解除する
unbind C-b

# tmuxのウィンドウモードをviにする
set-window-option -g mode-keys vi

# tmuxを256色表示できるようにする
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# ステータスバーを6秒毎に描画し直す
set-option -g status-interval 6

# ステータスバーの色を設定する
set-option -g status-bg "colour202"

# status line の文字色を指定する。
set-option -g status-fg "colour235"

# vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vimのキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# / でペインを垂直分割する
bind / split-window -h

# - でペインを水平分割する
bind - split-window -v

# window-statusを右寄せにする
set -g status-justify right

# windowのインデックスを1から始める
set -g base-index 1

set-option -g mouse on
# macOSの場合のみ、コピーしたテキストをクリップボードに送る設定を適用
if-shell 'test "$(uname)" = "Darwin"' {
    unbind -T copy-mode-vi Enter
    bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
    bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
    bind-key -T copy-mode-vi v send-keys -X begin-selection
    bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
}

# スクロールアップするとコピーモードに入る
bind-key -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"

# 最後までスクロールダウンするとコピーモードを抜ける
bind-key -n WheelDownPane select-pane -t= \; send-keys -M

# List of plugins
#set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-battery'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
#run -b '~/.tmux/plugins/tpm/tpm'
